### ISSUE TITLE
Web Page - Access Instructions

### ISSUE THREAD

**Issue by softcraftsman** [fabriciosanchez/sas#6]
Provide a web page with access instructions for a selected folder.

- [] CLI Access
- [] Storage Explorer Access

![4  FabricioGenomicFiles](https://user-images.githubusercontent.com/3756829/148451355-dfde1461-f832-40c6-b27c-a5868a690704.png)
![5  FabricioGenomicFiles-Modal-Direct](https://user-images.githubusercontent.com/3756829/148451372-913af704-edb1-4886-9c5d-ace0ef308dd4.png)

**Comment by SvenAelterman** [comment]
az cli access was removed.
